jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Build project
      run: .github/scripts/gradlew_recursive.sh assembleDebug
    - continue-on-error: true
      name: Zip artifacts
      run: zip -r assemble.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar'
        '**/build/*.so'
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: assemble
        path: assemble.zip
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
